function loadpg(mname, dmvdo,sp1,sp2,sp3,sp4,sp5) {
    document.getElementById("mname").innerText = mname;
    document.getElementById("demovdo").src = dmvdo;

    document.getElementsByClassName("spareimgs")[0].src=sp1;
    document.getElementsByClassName("spareimgs")[1].src=sp2;
    document.getElementsByClassName("spareimgs")[2].src=sp3;
    document.getElementsByClassName("spareimgs")[3].src=sp4;
    document.getElementsByClassName("spareimgs")[4].src=sp5;
    document.getElementById("mainimg").src=sp5;
}
function loaddata(value1,value2,value3,value4,value5){
    document.getElementById("model").innerText=value1;
    document.getElementById("power").innerText=value2;
    document.getElementById("rota").innerText=value3;
    document.getElementById("start").innerText=value4;
    document.getElementById("fuel").innerText=value5;
}
function hideextradata(){
    for(let i=3;i>=0;i--){ document.getElementsByClassName("attachrmv")[i].style.display="none";}  
}
function imgsetter(setimg) {
    document.getElementById("mainimg").src = setimg;
}
function collagehide(){
    document.getElementsByClassName("collage")[0].style.display="none";
}
function askprice(){
    let msgdt = "*Message From Website* \n Requesting Price of "+document.getElementById("model").innerText;
    sendmsg(msgdt);
}
function viewloadcont(subj){
    for (let i = 0; i < 5; i++) {
        document.getElementsByClassName("spareimgs")[i].addEventListener("mouseover", function () { imgsetter(this.src) });
    }
    
    let mname = "Name Loading..."
    let spimg1 = "./weederimg/" + subj + "F.png";
    let spimg2 = "./weederimg/" + subj + "R.png";
    let spimg3 = "./weederimg/" + subj + "B.png";
    let spimg4 = "./weederimg/" + subj + "L.png";
    let spimg5 = "./weederimg/" + subj + "MR.png";
    let dmvdo = "";
    let yturl = "https://www.youtube.com/embed/";
    
    switch (subj) {
        // Weeders
        case "732DB": mname = "Shaurya 732 10HP Lombardini Kohler Diesel Self Start Power Weeder";
        dmvdo = yturl + "7JGLbOXNWMU?si=LdDcH3b3evkRGDmt";
        value1="Shaurya 732 Lombardini";
        value2="10HP";
        value3="3ft Tilling Rota, 3ft Develop Rota";
        value4="Self Start";
        value5="Diesel";
        break;
        case "732DA": mname = "Shaurya 732 9HP Diesel Self Start Power Weeder";
        dmvdo = yturl + "5RtXjNZMg8o?si=C3ALhYrTIDFLttKj";
        value1="Shaurya 732";
        value2="9HP";
        value3="3ft Tilling Rota, 3ft Develop Rota";
        value4="Self Start";
        value5="Diesel";
        break;
        case "732P": mname = "Shaurya 732 9HP Petrol Self Start Power Weeder";
        dmvdo = yturl + "mFdJfTZo0fw?si=4r77kTEpmMHoFJQZ";
        value1="Shaurya 732P";
        value2="7HP";
        value3="3ft Tilling Rota, 3ft Develop Rota";
        value4="Self Start";
        value5="Petrol";
        break;
        case "D531RTF": mname = "D-531 RTF Self Start Power Weeder";
        dmvdo = yturl + "1ZUlXihir1Y?si=XutDUybCuAJVvgU9";
        value1="D-531 RT-F";
        value2="9HP";
        value3="3ft,4ft Front Tilling Rota & 2ft,3ft Rear Tilling Rota & 2ft Develop Rota";
        value4="Self Start";
        value5="Diesel";
        break;
        case "D531RT": mname = "D-531 RT Self Start Power Weeder";
        dmvdo = yturl + "mFdJfTZo0fw?si=4r77kTEpmMHoFJQZ";
        value1="D-531 RT";
        value2="9HP";
        value3="3ft,4ft,5ft Tilling Rota & 2ft Develop Rota";
        value4="Self Start";
        value5="Diesel";
        break;
        case "Shakti": mname = "Shakti 7HP Diesel Rear Tiller";
        dmvdo = yturl + "16dHE88djtg?si=iMvAgU2fBUcnoaXw";
        value1="Shakti";
        value2="7HP";
        value3="3ft,4ft Tilling Rota & 2ft, 3ft Develop Rota";
        value4="Manual Start";
        value5="Diesel";
        break;
        case "D531E": mname = "D-531 E Self Start Power Weeder";
        dmvdo =  yturl + "P_2dQT5FzHg?si=oc_lPSpVaBFkzA-D";
        value1="D-531E";
        value2="9HP";
        value3="3ft,4ft,5ft Tilling Rota";
        value4="Self Start";
        value5="Diesel";
        break;
        case "D531M": mname = "D-531 Manual Start Power Weeder";
        dmvdo =  yturl + "P_2dQT5FzHg?si=oc_lPSpVaBFkzA-D";
        value1="D-531M";
        value2="9HP";
        value3="3ft,4ft,5ft Tilling Rota";
        value4="Manual Start";
        value5="Diesel";
        //lack of photos
            spimg1="./weederimg/D531EF.png";
            spimg3="./weederimg/D531EB.png";
            spimg5="./weederimg/D531EMR.png";
        //lack of photos
        break;
        case "D105": mname = "D-105 Self Start Power Weeder";
        dmvdo =  yturl + "P_2dQT5FzHg?si=oc_lPSpVaBFkzA-D";
        value1="D-105E";
        value2="7HP";
        value3="3ft,4ft Tilling Rota";
        value4="Self Start";
        value5="Diesel";
        //lack of photos
        spimg3="./weederimg/D531EB.png";
    //lack of photos
        break;
        case "D90": mname = "D90 Manual Power Weeder";
        dmvdo =  yturl + "MJrLE2BHUQk?si=_Fa2Qn6MEgYPPRtj";
        value1="D-90";
        value2="4.5HP/7HP";
        value3="2ft,3ft,4ft Tilling Rota";
        value4="Manual Start";
        value5="Diesel";
        break;
        case "G105": mname = "G105 7HP Petrol Power Weeder";
        dmvdo = yturl + "H6ZD5_s-U1M?si=M0C86MwXWVWVb1Vy";
        value1="G-105";
        value2="7HP";
        value3="2ft,3ft,4ft Tilling Rota";
        value4="Manual Start";
        value5="Petrol";
        break;
        case "G500": mname = "G500 7HP Chain-Belt Petrol Power Weeder";
        dmvdo = yturl + "xcPlyozFhvs?si=2nuArv624O7YM2th";
        value1="G-500";
        value2="7HP";
        value3="2ft,3ft Tilling Rota";
        value4="Manual Start";
        value5="Petrol";
        break;
        case "Taro": mname = "7HP Petrol Taro Reaper";
        dmvdo = yturl + "MLA4ZynFBkk?si=TQr8HrLNqtHbgJ5n";
        value1="Taro Reaper";
        value2="7HP";
        value3="4 Line Reaper";
        value4="Manual Start";
        value5="Petrol";
        document.getElementById("thrdrow").innerText="Reaper Size";
        break;
        // Accessories
        case "Pass": mname = "Pass Attachment";
        dmvdo = yturl + "sC01ce8L01Y?si=ZMMmQFc6_xB4wW5E";
        value1=mname;
        value2="";
        value3="2ft, 2.5ft, 3ft(2 Pass Free)";
        value4="";
        value5="";
        document.getElementById("thrdrow").innerText="Adjustable Sizes";
        document.getElementsByClassName("attachrmv")[3].style.display="none";
        document.getElementsByClassName("attachrmv")[2].style.display="none";
        document.getElementsByClassName("attachrmv")[0].style.display="none";
        break;
        case "Ridger": mname = "Ridger Attachment";
        dmvdo = yturl + "ikEe8gNHWpI?si=brgf0bvOMsPCCVHG";
        break;
        case "Plough": mname = "Plough Attachment";
        dmvdo = yturl + "F_CsIjFd8Ho?si=OeTsmXnaOX0kmxw-";
        break;
        case "SeedDrill": mname = "Seed Drill Attachment";
        dmvdo = yturl + "QsWrVEKNiwQ?si=0jyGi3ktQdRltBfc";
        value1=mname;
        value2="";
        value3="Single Box, Three Line Seed Drill";
        value4="";
        value5="";
        document.getElementById("thrdrow").innerText="Description";
        document.getElementsByClassName("attachrmv")[3].style.display="none";
        document.getElementsByClassName("attachrmv")[2].style.display="none";
        document.getElementsByClassName("attachrmv")[0].style.display="none";
        break;
        case "HTP": mname = "HTP Attachment";
        dmvdo = yturl + "a5dNRgAh7rg?si=5QrJIDsA9D8fUcUV";
        break;
        case "Pump": mname = "Pump Attachment";
        dmvdo = yturl + "eMl3RnPqpC0?si=cAOY6oXQLWPfC1fy";
        break;
        case "Trolley": mname = "Trolley Attachment";
        dmvdo = yturl + "MuUlGXbX_OY?si=fQzBpxphpw4iOYvs";
        value1=mname;
        value2="";
        value3="4ft X 5ft";
        value4="";
        value5="";
        document.getElementById("thrdrow").innerText="Dimensions";
        document.getElementsByClassName("attachrmv")[3].style.display="none";
        document.getElementsByClassName("attachrmv")[2].style.display="none";
        document.getElementsByClassName("attachrmv")[0].style.display="none";
        break;
        case "Seat": mname = "Seat Attachment";
        dmvdo = yturl + "c9zAr5b7Gug?si=i14y24l3FPC8EhkC";
        break;
        case "Reaper": mname = "Reaper Attachment";
        dmvdo = yturl + "1TwO8kgqth4?si=mrJdMNo29gvrnu8Q";
        value1=mname;
        value2="";
        value3="3 Line Reaper Attachment";
        value4="";
        value5="";
        document.getElementById("thrdrow").innerText="Reaper Size";
        document.getElementsByClassName("attachrmv")[3].style.display="none";
        document.getElementsByClassName("attachrmv")[2].style.display="none";
        document.getElementsByClassName("attachrmv")[0].style.display="none";
        break;
        // BrushCutters
        case "35ccBP": mname = "35cc 4Stroke Backpack BrushCutter";
        dmvdo = yturl + "Tp5mqqYL0iw?si=VhZ2TWIH-DpGsG0W&amp;start=3";
        value1=mname;
        value2="35cc";
        value3="3 Teeth Blade,Paddy Harvester, Trimmer Head";
        value4="Manual Start";
        value5="Petrol";
        document.getElementById("thrdrow").innerText="Free Accessories";
        collagehide();
        break;
        case "35ccSP": mname = "35cc 4Stroke Sidepack BrushCutter";
        dmvdo = yturl + "-DXGx0pT1BA?si=IITXjPR4l0OomtOw";
        value1=mname;
        value2="35cc";
        value3="3 Teeth Blade,Paddy Harvester, Trimmer Head";
        value4="Manual Start";
        value5="Petrol";
        document.getElementById("thrdrow").innerText="Free Accessories";
        collagehide();
        break;
        case "31ccBP": mname = "31cc 4Stroke Backpack BrushCutter";
        dmvdo = yturl + "FRggdM4O2CM?si=IIhLaythcCqzWCMX";
        value1=mname;
        value2="31cc";
        value3="3 Teeth Blade,Paddy Harvester, Trimmer Head";
        value4="Manual Start";
        value5="Petrol";
        document.getElementById("thrdrow").innerText="Free Accessories";
        collagehide();
        break;
        case "31ccSP": mname = "31cc 4Stroke Sidepack BrushCutter";
        dmvdo = yturl + "r6bCDFLm8QI?si=6toLT0B7mpqPfMnm&amp;start=9";
        value1=mname;
        value2="31cc";
        value3="3 Teeth Blade,Paddy Harvester, Trimmer Head";
        value4="Manual Start";
        value5="Petrol";
        document.getElementById("thrdrow").innerText="Free Accessories";
        collagehide();
        break;
        case "52ccBP": mname = "52cc 2Stroke Backpack BrushCutter";
        dmvdo = yturl + "4TXLgXcwstY?si=eRL89t0Zz0QX4JnZ";
        value1=mname;
        value2="52cc";
        value3="3 Teeth Blade,Paddy Harvester, Trimmer Head";
        value4="Manual Start";
        value5="Petrol";
        document.getElementById("thrdrow").innerText="Free Accessories";
        collagehide();
        break;
        case "52ccSP": mname = "52cc 2Stroke Sidepack BrushCutter";
        dmvdo = yturl + "j_2SJx7Q740?si=yjpFliJbhDdPfeYI";
        value1=mname;
        value2="52cc";
        value3="3 Teeth Blade,Paddy Harvester, Trimmer Head";
        value4="Manual Start";
        value5="Petrol";
        document.getElementById("thrdrow").innerText="Free Accessories";
        collagehide();
        break;
        // BC Attachments
        case "BCRota": mname = "Rotavator For Brush Cutter";
        dmvdo = yturl + "GSHFeuLiYZI?si=e3MkOnmIHOmLutE5";
        break;
        case "3TBLade": mname = "3 Teeth Blade For Brush Cutter";
        dmvdo = yturl + "cnhuDNQLo0Q?si=wjSYVLD8f9HVx-k4";
        break;
        case "80TBlade": mname = "80 Teeth Blade Brush Cutter";
        dmvdo = yturl + "1c6ciW-qyYU?si=EG5PkePEO6bH1evL";
        break;
        case "SteelTrimmer": mname = "Steel Trimmer Head For Brush Cutter";
        dmvdo = yturl + "388mgdoFNNM?si=z1vuiweu9TK6tV7f&amp;start=456";
        break;
        case "ChainsawAttach": mname = "Chainsaw Attachment For Brush Cutter";
        dmvdo = yturl + "bnvid5y6ei8?si=znCV4vdZri8Q5Q10";
        break;
        case "Hedge": mname = "Trimmer Hedge For Brush Cutter";
        dmvdo = yturl + "S7jAeVS9dkQ?si=u_wfwxU-51atOhXc&amp;start=63";
        break;
        // Earth Augers
        case "52ccEA": mname = "52cc Earth Auger";
        dmvdo = yturl + "o784QXMKFng?si=fvW0cbO0E6tZv77g";
        value1=mname;
        value2="52cc";
        value3="";
        value4="Manual Start";
        value5="Petrol";
        document.getElementsByClassName("attachrmv")[1].style.display="none";
        collagehide();
        break;
        case "63ccEA": mname = "63cc Earth Auger";
        dmvdo = yturl + "fmYo-i4pb1Y?si=qhzOl4GBwhazUIUw";
        value1=mname;
        value2="63cc";
        value3="";
        value4="Manual Start";
        value5="Petrol";
        document.getElementsByClassName("attachrmv")[1].style.display="none";
        collagehide();
        break;
        case "63ccSPEA": mname = "63cc Trolley Earth Auger";
        dmvdo = yturl + "MKM7q48T8pE?si=hctl_0Vd3fL9SYah";
        value1=mname;
        value2="63cc";
        value3="";
        value4="Manual Start";
        value5="Petrol";
        document.getElementsByClassName("attachrmv")[1].style.display="none";
        collagehide();
        break;
        case "EABit": mname = "Earth Auger Bits";
        dmvdo = yturl + "MKM7q48T8pE?si=hctl_0Vd3fL9SYah";
        collagehide();
        break;
        //Other Machinery
        case "Chainsaw": mname = "Chainsaw";
        dmvdo = yturl + "J3AT5gWeaZE?si=nqc2KcTaO-tUJ5io";
        value1=mname;
        value2="62cc";
        value3="";
        value4="Manual Start";
        value5="Petrol";
        document.getElementsByClassName("attachrmv")[1].style.display="none";
        collagehide();
        break;
        case "Chaffcutter": mname = "Chaff Cutter";
        dmvdo = yturl + "sAgUElqAV6E?si=QJ7GgEuoeUowgBuN";
        value1=mname;
        value2="3HP Motor";
        value3="";
        value4="";
        value5="Electric";
        document.getElementsByClassName("attachrmv")[1].style.display="none";
        document.getElementsByClassName("attachrmv")[2].style.display="none";
        collagehide();
        break;
    }
    let attachments = ["Ridger", "Plough","HTP", "Pump",  "Seat", "EABit","Hedge","BCRota","3TBlade","80TBlade","SteelTrimmer","ChainsawAttach"];
    if(attachments.includes(subj)){
        value1=mname;
        value2="";
        value3="";
        value4="";
        value5="";
        hideextradata("all");
    }
    loadpg(mname, dmvdo, spimg1, spimg2, spimg3, spimg4, spimg5);
    loaddata(value1,value2,value3,value4,value5);
    visit("#top");
}